# Generated by Django 6.0.3 on 2026-03-07 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quilometragem', models.IntegerField()),
                ('combustivel', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diesel'), ('eletrico', 'Elétrico'), ('hibrido', 'Híbrido')], max_length=20)),
                ('transmissao', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], max_length=20)),
                ('cor', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='veiculos/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autolux.marca')),
            ],
        ),
    ]
