# Generated by Django 6.0.3 on 2026-03-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='transmissao',
            field=models.CharField(choices=[('manual/automático', 'Manual/Automático'), ('manual', 'Manual'), ('automatico', 'Automático')], max_length=20),
        ),
    ]
